language: php

php:
  - 8.1

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - cp .env.example .env  # Настроить файл окружения, если требуется
  - php artisan key:generate  # Для Laravel, если используется
  - php artisan migrate --seed  # Применить миграции, если нужны

script:
  - vendor/bin/phpunit --coverage-text --colors=never
